version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./main"
    volumes:
      - ./logs/app:/app/logs/app
    ports:
      - "8000:8000"
      - "8080:8080"
    networks:
      - my_network
    restart: always
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  my_network: